services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi8
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./mongodb:/data/db
    networks:
      - backend

volumes:
  mongodb:

networks:
  backend:
